const API="/api/v1",$=id=>document.getElementById(id);let manufacturers=[],currentProfile=null,profiles=[];
async function loadVersion(){try{const r=await fetch("/build-info.json",{cache:"no-store"});if(!r.ok)return;const b=await r.json();const v=b.version||b.tag;if(v)$("versionButton").textContent=String(v).startsWith("v")?String(v):`v${v}`}catch{}}

async function api(p,o={}){const r=await fetch(API+p,{credentials:"same-origin",headers:{"Content-Type":"application/json"},...o});let b={};try{b=await r.json()}catch{}if(r.status===401){showLogin();throw Error(b.detail||"Choose your name")}if(!r.ok)throw Error(b.detail||`Request failed (${r.status})`);return b}
function showLogin(){$("loginView").classList.remove("hidden");$("appView").classList.add("hidden")}function showApp(){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden")}function page(n){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===`page-${n}`));document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===n));scrollTo(0,0)}
const num=v=>v===""||v==null?null:Number(v),val=(id,v)=>$(id).value=v??"",esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function boot(){loadVersion();try{currentProfile=(await api("/auth/me")).profile;showApp();const [pr,m]=await Promise.all([api("/profiles"),api("/reference/manufacturers")]);profiles=pr.profiles||[];manufacturers=m.manufacturers||[];renderProfiles();renderMakers();fillTargetMakes();await Promise.all([loadSettings(),loadDiscovery(),loadTargets(),loadResults(),loadInterested()])}catch{showLogin()}}
function renderProfiles(){$("profileSelect").innerHTML=profiles.map(p=>`<option value="${p.id}" ${p.id===currentProfile.id?"selected":""}>${esc(p.name)}</option>`).join("")}
$("profileSelect").onchange=async e=>{currentProfile=(await api("/auth/switch",{method:"POST",body:JSON.stringify({profile_id:+e.target.value})})).profile;await boot()};
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").classList.add("hidden");$("loginChoices").classList.add("hidden");const name=$("loginName").value.trim(),r=await api("/auth/name",{method:"POST",body:JSON.stringify({name,create:false})});if(r.status==="ok")return boot();showUnknown(r.entered_name,r.suggestions||[])};
function showUnknown(name,s){$("loginError").textContent=`"${name}" is not an existing name.`;$("loginError").classList.remove("hidden");let h=s.length?`<p class="muted">Did you mean?</p>${s.map(p=>`<button type="button" class="secondary use-name" data-name="${esc(p.name)}">Use ${esc(p.name)}</button>`).join("")}`:"";h+=`<button type="button" class="primary" id="addName">Add "${esc(name)}" as a new user</button>`;$("loginChoices").innerHTML=h;$("loginChoices").classList.remove("hidden");document.querySelectorAll(".use-name").forEach(b=>b.onclick=()=>{$("loginName").value=b.dataset.name;$("loginForm").requestSubmit()});$("addName").onclick=async()=>{if(confirm(`Add "${name}" as a new CarFinder user?`)){await api("/auth/name",{method:"POST",body:JSON.stringify({name,create:true})});await boot()}}}
$("logoutButton").onclick=async()=>{try{await api("/auth/logout",{method:"POST"})}catch{}$("loginName").value="";showLogin()};document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>page(b.dataset.go));
function renderMakers(sel=[]){$("manufacturerList").innerHTML=manufacturers.map(m=>`<label><input type="checkbox" value="${esc(m)}" ${sel.includes(m)?"checked":""}>${esc(m)}</label>`).join("")}function fillTargetMakes(){$("targetMake").innerHTML=manufacturers.map(m=>`<option>${esc(m)}</option>`).join("")}
async function loadSettings(){const s=await api("/settings");for(const [id,k] of [["settingsPostcode","postcode"],["settingsRadius","radius_miles"],["settingsMaxPrice","max_price"],["settingsMaxMileage","max_mileage"],["settingsMinYear","min_year"],["settingsSeats","min_seats"],["settingsPower","min_power_bhp"]])val(id,s[k]);if(!$("discoveryRadius").value)val("discoveryRadius",s.radius_miles)}
$("settingsForm").onsubmit=async e=>{e.preventDefault();await api("/settings",{method:"PUT",body:JSON.stringify({postcode:$("settingsPostcode").value,radius_miles:num($("settingsRadius").value)||50,max_price:num($("settingsMaxPrice").value),max_mileage:num($("settingsMaxMileage").value),min_year:num($("settingsMinYear").value),min_seats:num($("settingsSeats").value),min_power_bhp:num($("settingsPower").value)})});$("settingsSaved").textContent="Saved";setTimeout(()=>$("settingsSaved").textContent="",1500)};
async function loadDiscovery(){const d=await api("/discovery");renderMakers(d.manufacturers||[]);for(const [id,k] of [["discoveryFuel","fuel"],["discoveryBody","body_type"],["discoveryGearbox","transmission"],["discoveryMinPrice","min_price"],["discoveryMaxPrice","max_price"],["discoveryMileage","max_mileage"],["discoveryYear","min_year"],["discoverySeats","seats"],["discoveryPower","min_power_bhp"],["discoveryRadius","radius_miles"]])val(id,d[k])}
function disc(){return{manufacturers:[...document.querySelectorAll("#manufacturerList input:checked")].map(x=>x.value),fuel:$("discoveryFuel").value||null,body_type:$("discoveryBody").value||null,transmission:$("discoveryGearbox").value||null,min_price:num($("discoveryMinPrice").value),max_price:num($("discoveryMaxPrice").value),max_mileage:num($("discoveryMileage").value),min_year:num($("discoveryYear").value),seats:num($("discoverySeats").value),min_power_bhp:num($("discoveryPower").value),radius_miles:num($("discoveryRadius").value)}}
$("discoveryForm").onsubmit=async e=>{e.preventDefault();await api("/discovery",{method:"PUT",body:JSON.stringify(disc())});$("discoverySaved").textContent="Saved"};
$("startSearchButton").onclick=async()=>{const box=$("searchStatus"),btn=$("startSearchButton");box.classList.remove("hidden");box.textContent="Searching live manufacturer stock…";btn.disabled=true;try{await api("/discovery",{method:"PUT",body:JSON.stringify(disc())});const r=await api("/search/start",{method:"POST"});box.textContent=r.message+(r.failures?.length?` Problems: ${r.failures.join(" | ")}`:"");await loadResults();await loadInterested();if(r.status==="complete")page("results")}catch(e){box.textContent=e.message}finally{btn.disabled=false}};
async function loadTargets(){const a=(await api("/targets")).targets||[];$("targetList").innerHTML=a.map(t=>`<article class="target-card"><h3>${esc(t.make)} ${esc(t.model)}</h3><p class="muted">${t.created_by?`Added by ${esc(t.created_by)}`:"Shared target"}</p><button class="secondary" onclick="deleteTarget(${t.id})">Delete</button></article>`).join("");$("targetsEmpty").classList.toggle("hidden",!!a.length);$("clearTargetsButton").classList.toggle("hidden",!a.length)}
window.deleteTarget=async id=>{if(confirm("Delete this target vehicle?")){await api(`/targets/${id}`,{method:"DELETE"});loadTargets()}};$("clearTargetsButton").onclick=async()=>{if(confirm("Clear ALL target vehicles?")){await api("/targets",{method:"DELETE"});loadTargets()}};
function openTarget(){$("targetForm").reset();$("targetDialog").showModal()}$("addTargetButton").onclick=openTarget;$("emptyAddTargetButton").onclick=openTarget;$("cancelTargetButton").onclick=()=>$("targetDialog").close();$("closeTargetDialog").onclick=()=>$("targetDialog").close();
$("targetForm").onsubmit=async e=>{e.preventDefault();const o={};for(const [k,id] of [["max_price","targetMaxPrice"],["max_mileage","targetMaxMileage"],["min_year","targetMinYear"]]){const v=num($(id).value);if(v!=null)o[k]=v}await api("/targets",{method:"POST",body:JSON.stringify({make:$("targetMake").value,model:$("targetModel").value,body_type:$("targetBody").value||null,overrides:o})});$("targetDialog").close();loadTargets()};
function card(v){const status=v.status||"neutral";return`<article class="vehicle-card"><div class="eyebrow">${esc(v.source||"Vehicle")}</div><h3>${esc([v.make,v.model,v.trim].filter(Boolean).join(" "))}</h3><div class="meta-row">${v.price!=null?`<span class="pill">£${Number(v.price).toLocaleString()}</span>`:""}${v.mileage!=null?`<span class="pill">${Number(v.mileage).toLocaleString()} miles</span>`:""}${v.distance_miles!=null?`<span class="pill">${Math.round(v.distance_miles)} miles away</span>`:""}${v.price_points>1?`<span class="pill">${v.price_points} price points</span>`:""}</div><p class="muted">${esc(v.dealer_name||"Dealer not recorded")} · ${esc(v.registration||"")}</p><textarea id="note-${v.id}" rows="2" placeholder="Family notes">${esc(v.notes||"")}</textarea><div class="card-actions"><button class="${status==="interested"?"primary":"secondary"}" onclick="setState(${v.id},'interested')">Interested</button><button class="${status==="rejected"?"primary":"secondary"}" onclick="setState(${v.id},'rejected')">Not Suitable</button><button class="secondary" onclick="setState(${v.id},'neutral')">Clear</button>${v.url?`<a class="secondary" target="_blank" rel="noopener" href="${esc(v.url)}">Advert</a>`:""}</div>${v.updated_by?`<p class="muted">Last reviewed by ${esc(v.updated_by)}</p>`:""}</article>`}
window.setState=async(id,status)=>{await api(`/results/${id}/state`,{method:"PUT",body:JSON.stringify({status,notes:$(`note-${id}`)?.value||""})});await Promise.all([loadResults(),loadInterested()])};
async function loadResults(){const a=(await api("/results")).results||[];$("resultsEmpty").classList.toggle("hidden",!!a.length);$("resultList").innerHTML=a.map(card).join("")}
async function loadInterested(){const a=(await api("/interested")).results||[];$("interestedEmpty").classList.toggle("hidden",!!a.length);$("interestedList").innerHTML=a.map(card).join("")}
boot();
