const API="/api/v1",$=id=>document.getElementById(id);let manufacturers=[],profiles=[],currentProfile=null;
async function api(path,options={}){const r=await fetch(API+path,{credentials:"same-origin",headers:{"Content-Type":"application/json"},...options});let body={};try{body=await r.json()}catch{}if(r.status===401){showLogin();throw Error(body.detail||"Choose your name")}if(!r.ok)throw Error(body.detail||`Request failed (${r.status})`);return body}
async function loadVersion(){try{const r=await fetch("/build-info.json",{cache:"no-store"});if(r.ok){const b=await r.json(),v=b.version||b.tag;if(v)$("versionButton").textContent=String(v).startsWith("v")?v:`v${v}`}}catch{}}
function showLogin(){$("loginView").classList.remove("hidden");$("appView").classList.add("hidden")}function showApp(){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden")}function page(name){document.querySelectorAll(".page").forEach(x=>x.classList.toggle("active",x.id===`page-${name}`));document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===name));scrollTo(0,0)}
const num=v=>v===""||v==null?null:Number(v),val=(id,v)=>$(id).value=v??"",esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function boot(){loadVersion();try{currentProfile=(await api("/auth/me")).profile;showApp();const [pr,m]=await Promise.all([api("/profiles"),api("/reference/manufacturers")]);profiles=pr.profiles||[];manufacturers=m.manufacturers||[];renderProfiles();await Promise.all([loadSettings(),loadDiscovery(),loadResults(),loadMyCars(),loadUnsuitable()])}catch{showLogin()}}
function renderProfiles(){$("profileSelect").innerHTML=profiles.map(p=>`<option value="${p.id}" ${p.id===currentProfile.id?"selected":""}>${esc(p.name)}</option>`).join("")}
$("profileSelect").onchange=async e=>{currentProfile=(await api("/auth/switch",{method:"POST",body:JSON.stringify({profile_id:+e.target.value})})).profile;await boot()};
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginError").classList.add("hidden");$("loginChoices").classList.add("hidden");const name=$("loginName").value.trim(),r=await api("/auth/name",{method:"POST",body:JSON.stringify({name,create:false})});if(r.status==="ok")return boot();showUnknown(r.entered_name,r.suggestions||[])};
function showUnknown(name,s){$("loginError").textContent=`"${name}" is not an existing name.`;$("loginError").classList.remove("hidden");let h=s.length?`<p class="muted">Did you mean?</p>${s.map(p=>`<button type="button" class="secondary use-name" data-name="${esc(p.name)}">Use ${esc(p.name)}</button>`).join("")}`:"";h+=`<button type="button" class="primary" id="addName">Add "${esc(name)}" as a new user</button>`;$("loginChoices").innerHTML=h;$("loginChoices").classList.remove("hidden");document.querySelectorAll(".use-name").forEach(b=>b.onclick=()=>{$("loginName").value=b.dataset.name;$("loginForm").requestSubmit()});$("addName").onclick=async()=>{if(confirm(`Add "${name}" as a new CarFinder user?`)){await api("/auth/name",{method:"POST",body:JSON.stringify({name,create:true})});await boot()}}}
$("logoutButton").onclick=async()=>{try{await api("/auth/logout",{method:"POST"})}catch{}$("loginName").value="";showLogin()};document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>page(b.dataset.page));
function renderMakers(selected=[]){$("manufacturerList").innerHTML=manufacturers.map(m=>`<label><input type="checkbox" value="${esc(m)}" ${selected.includes(m)?"checked":""}>${esc(m)}</label>`).join("");document.querySelectorAll("#manufacturerList input").forEach(x=>x.onchange=updateSelectedMakers);updateSelectedMakers()}
function selectedMakers(){return[...document.querySelectorAll("#manufacturerList input:checked")].map(x=>x.value)}function updateSelectedMakers(){const a=selectedMakers();$("manufacturerSelected").textContent=a.length?a.join(", "):"None";$("manufacturerSummary").textContent=a.length?`${a.length} selected`:"Choose manufacturers"}
async function loadSettings(){const s=await api("/settings");for(const [id,k] of [["settingsPostcode","postcode"],["settingsRadius","radius_miles"],["settingsMaxPrice","max_price"],["settingsMaxMileage","max_mileage"],["settingsMinYear","min_year"],["settingsSeats","min_seats"],["settingsPower","min_power_bhp"]])val(id,s[k]);if(!$("discoveryRadius").value)val("discoveryRadius",s.radius_miles)}
$("settingsForm").onsubmit=async e=>{e.preventDefault();await api("/settings",{method:"PUT",body:JSON.stringify({postcode:$("settingsPostcode").value,radius_miles:num($("settingsRadius").value)||50,max_price:num($("settingsMaxPrice").value),max_mileage:num($("settingsMaxMileage").value),min_year:num($("settingsMinYear").value),min_seats:num($("settingsSeats").value),min_power_bhp:num($("settingsPower").value)})});$("settingsSaved").textContent="Saved";setTimeout(()=>$("settingsSaved").textContent="",1400)};
async function loadDiscovery(){const d=await api("/discovery");renderMakers(d.manufacturers||[]);for(const [id,k] of [["discoveryFuel","fuel"],["discoveryBody","body_type"],["discoveryGearbox","transmission"],["discoveryMinPrice","min_price"],["discoveryMaxPrice","max_price"],["discoveryMileage","max_mileage"],["discoveryYear","min_year"],["discoverySeats","seats"],["discoveryPower","min_power_bhp"],["discoveryRadius","radius_miles"]])val(id,d[k])}
function discoveryPayload(){return{manufacturers:selectedMakers(),fuel:$("discoveryFuel").value||null,body_type:$("discoveryBody").value||null,transmission:$("discoveryGearbox").value||null,min_price:num($("discoveryMinPrice").value),max_price:num($("discoveryMaxPrice").value),max_mileage:num($("discoveryMileage").value),min_year:num($("discoveryYear").value),seats:num($("discoverySeats").value),min_power_bhp:num($("discoveryPower").value),radius_miles:num($("discoveryRadius").value)}}
$("discoveryForm").onsubmit=async e=>{e.preventDefault();await api("/discovery",{method:"PUT",body:JSON.stringify(discoveryPayload())});$("discoverySaved").textContent="Saved";setTimeout(()=>$("discoverySaved").textContent="",1400)};
$("startSearchButton").onclick=async()=>{const box=$("searchStatus"),btn=$("startSearchButton");box.classList.remove("hidden");box.textContent="Searching live manufacturer stock…";btn.disabled=true;try{await api("/discovery",{method:"PUT",body:JSON.stringify(discoveryPayload())});const r=await api("/search/start",{method:"POST"});box.textContent=r.message+(r.failures?.length?` Problems: ${r.failures.join(" | ")}`:"");await Promise.all([loadResults(),loadMyCars()]);if(r.status==="complete")page("results")}catch(e){box.textContent=e.message}finally{btn.disabled=false}};
function priceText(v){if(v.price==null)return"Price unknown";let s=`£${Number(v.price).toLocaleString()}`;if(v.in_my_cars&&v.initial_price!=null&&v.price_change!=null&&v.price_change!==0){const d=Math.abs(v.price_change).toLocaleString();s+=v.price_change<0?` <span class="price-down">↓ £${d}</span>`:` <span class="price-up">↑ £${d}</span>`}return s}
function facts(v){return[priceText(v),v.mileage!=null?`${Number(v.mileage).toLocaleString()} miles`:null,v.distance_miles!=null?`${Math.round(v.distance_miles)} miles away`:null,v.dealer_name||null].filter(Boolean).map(x=>`<span>${x}</span>`).join("")}
function resultRow(v){return`<article class="result-row ${v.in_my_cars?"saved-hit":""}"><div class="row-main"><div><div class="car-title">${esc([v.make,v.model,v.trim].filter(Boolean).join(" "))}</div><div class="car-sub">${esc(v.registration)}${v.in_my_cars?' · <span class="saved-label">IN MY CARS</span>':""}</div></div><div class="facts">${facts(v)}</div><div class="row-actions">${v.in_my_cars?"":`<button class="primary" onclick="addMyCar(${v.id})">Interested</button>`}<button class="danger" onclick="rejectCar(${v.id})">Not Suitable</button>${v.url?`<a class="secondary" href="${esc(v.url)}" target="_blank" rel="noopener">Advert</a>`:""}</div></div></article>`}
async function loadResults(){const a=(await api("/results")).results||[];$("resultsEmpty").classList.toggle("hidden",!!a.length);$("resultList").innerHTML=a.map(resultRow).join("")}window.addMyCar=async id=>{await api(`/my-cars/${id}`,{method:"POST"});await Promise.all([loadResults(),loadMyCars()])};window.rejectCar=async id=>{await api(`/unsuitable/${id}`,{method:"POST"});await Promise.all([loadResults(),loadMyCars(),loadUnsuitable()])};
function myCarRow(v){let change="";if(v.initial_price!=null&&v.price!=null){const d=v.price-v.initial_price;if(d<0)change=`<span class="price-down">Dropped £${Math.abs(d).toLocaleString()} from £${Number(v.initial_price).toLocaleString()}</span>`;else if(d>0)change=`<span class="price-up">Up £${d.toLocaleString()} from £${Number(v.initial_price).toLocaleString()}</span>`;else change=`No price change from £${Number(v.initial_price).toLocaleString()}`}return`<article class="saved-row"><div class="row-main"><div><div class="car-title">${esc([v.make,v.model,v.trim].filter(Boolean).join(" "))}</div><div class="car-sub">${esc(v.registration)} · Added by ${esc(v.added_by||"family")}</div></div><div class="facts">${[v.price!=null?`£${Number(v.price).toLocaleString()}`:null,v.mileage!=null?`${Number(v.mileage).toLocaleString()} miles`:null,v.dealer_name||null,change].filter(Boolean).map(x=>`<span>${x}</span>`).join("")}</div><div class="row-actions">${v.url?`<a class="secondary" href="${esc(v.url)}" target="_blank" rel="noopener">Advert</a>`:""}<button class="danger" onclick="removeMyCar(${v.id})">Remove</button></div></div><div class="notes-block"><textarea id="my-note-${v.id}" placeholder="Family notes">${esc(v.notes||"")}</textarea><button class="secondary" onclick="saveNote(${v.id})">Save note</button></div></article>`}
async function loadMyCars(){const a=(await api("/my-cars")).cars||[];$("myCarsEmpty").classList.toggle("hidden",!!a.length);$("myCarsList").innerHTML=a.map(myCarRow).join("")}window.removeMyCar=async id=>{if(confirm("Remove this car from My Cars?")){await api(`/my-cars/${id}`,{method:"DELETE"});await Promise.all([loadMyCars(),loadResults()])}};window.saveNote=async id=>{await api(`/my-cars/${id}/notes`,{method:"PUT",body:JSON.stringify({notes:$(`my-note-${id}`).value})})};
async function loadUnsuitable(){const a=(await api("/unsuitable")).cars||[];$("unsuitableEmpty").classList.toggle("hidden",!!a.length);$("unsuitableList").innerHTML=a.map(x=>`<article class="simple-row"><div class="row-main"><div><div class="car-title">${esc(x.registration)}</div><div class="car-sub">Marked unsuitable${x.rejected_by?` by ${esc(x.rejected_by)}`:""}</div></div><div></div><div class="row-actions"><button class="secondary" onclick="restoreUnsuitable('${esc(x.registration)}')">Allow again</button></div></div></article>`).join("")}window.restoreUnsuitable=async reg=>{await api(`/unsuitable/${encodeURIComponent(reg)}`,{method:"DELETE"});await loadUnsuitable()};
boot();
